name: myWorkflow
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Pull Repo
        run: git pull

      - name: Build and Deploy Docker Image
        run: |
          cd /home/ubuntu/Node_HelloWorld
          sudo docker compose up -d
          
