env:
  ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}

name: Push the Docker image to AWS ECR Repo and Deploy to ECS
on:
  workflow_dispatch:
    inputs:
      tf-cmd:
        description: 'The command to run terraform with'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
  push:
    branches:
    - main
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check privileged user
        id: priv-check
        working-directory: scripts
        run: |
          is_priv=$(./check-privileged-user.sh ${{ github.triggering_actor }})
          echo "is_priv=$is_priv" >> $GITHUB_OUTPUT
          if [ "$is_priv" = "true" ]; then
            echo "${{ github.triggering_actor }} is a privileged user."
          else
            echo "${{ github.triggering_actor }} is not a privileged user."
          fi   

      - name: Login to ECR
        if: ${{ github.event_name == 'push' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1
      
      - name: Build, tag and push image to ECR
        if: ${{ github.event_name == 'push' }}
        id: build-image
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Remove untagged images from ECR
        if: ${{ github.event_name == 'push' }}
        run: |
          IMAGES_TO_DELETE=$( aws ecr list-images --region ${{ secrets.AWS_REGION }} --repository-name ${{ secrets.ECR_REPO_NAME }} --filter "tagStatus=UNTAGGED" --query 'imageIds[*]' --output json )
          aws ecr batch-delete-image --region ${{ secrets.AWS_REGION }} --repository-name ${{ secrets.ECR_REPO_NAME }} --image-ids "$IMAGES_TO_DELETE" || true

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Initialize terraform
        working-directory: scripts/terraform
        run: terraform init
      
      - name: Run terraform plan
        id: tf-plan
        if: ${{ github.event_name == 'push' || github.event.inputs.tf-cmd == 'plan' }}
        working-directory: scripts
        run: |
          status=0
          ./terraform-check.sh || status="$?"
          if [ "$status" -eq 0 ]; then
            clean_deploy='true'
          elif [ "$status" -eq 1 ]; then
            clean_deploy='false'
          elif [ "$status" -eq 255 ]; then
            clean_deploy='err'
          fi
          echo "clean_deploy=$clean_deploy" >> $GITHUB_OUTPUT
      
      - name: Run terraform apply
        if: ${{ ( github.event_name == 'push' || github.event.inputs.tf-cmd == 'apply' ) }}
        working-directory: scripts/terraform
        run: |
          clean_deploy=${{ steps.tf-plan.outputs.clean_deploy }}
          priv_user=${{ steps.priv-check.outputs.is_priv }}
          if [ "$clean_deploy" = "true" ]; then
            echo 'Running terraform apply as it is a clean deploy.'
            terraform apply -auto-approve
          elif [ "$priv_user" = 'true' ]; then 
            echo 'Running terraform apply as the workflow was initiated by a privileged user.'
            terraform apply -auto-approve
          else 
            echo 'Failing the workflow as it was neither initiated by a privileged user nor was it a clean deploy.'
            exit 1
          fi
          