env:
  ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
  ECS_SERVICE: HelloWorld_Service
  ECS_CLUSTER: HelloWorld_Cluster
  ECS_TASK_DEFINITION: .aws/task-definition.json
  CONTAINER_NAME: Node_HelloWorld_Container

name: Push the Docker image to AWS ECR Repo
on:
  workflow_dispatch:
    inputs:
      tf-cmd:
        description: 'The command to run terraform with'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_GH_ACTIONS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1
      
      - name: Build, tag and push image to ECR
        id: build-image
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Initialize terraform
        working-directory: scripts/terraform
        run: terraform init
      
      - name: Run terraform plan
        if: ${{ github.event.inputs.tf-cmd == 'plan' }}
        working-directory: scripts
        run: ./terraform-check.sh
      
      - name: Run terraform apply
        if: ${{ github.event.inputs.tf-cmd == 'apply' }}
        working-directory: scripts/terraform
        run: terraform apply -auto-approve